import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service — Outbindr',
  description: 'Outbindr Terms of Service',
}

const EFFECTIVE = 'April 8, 2026'

export default function TermsPage() {
  return (
    <div style={{
      minHeight: '100vh', background: '#fff',
      fontFamily: "'IBM Plex Mono', monospace",
    }}>
      <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300;400;500;600&display=swap" rel="stylesheet" />

      {/* Nav */}
      <div style={{
        borderBottom: '1px solid #e8e8e8', padding: '14px 32px',
        display: 'flex', alignItems: 'center', gap: 12,
      }}>
        <Link href="/" style={{ textDecoration: 'none' }}>
          <span style={{ fontSize: 12, fontWeight: 700, letterSpacing: '0.18em', color: '#000' }}>
            OUTBINDR
          </span>
        </Link>
        <span style={{ fontSize: 10, color: '#ccc', letterSpacing: '0.08em' }}>/ TERMS OF SERVICE</span>
      </div>

      {/* Content */}
      <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 32px 80px' }}>
        <h1 style={{ fontSize: 18, fontWeight: 700, letterSpacing: '0.1em', color: '#000', marginBottom: 6 }}>
          TERMS OF SERVICE
        </h1>
        <p style={{ fontSize: 10, color: '#aaa', letterSpacing: '0.08em', marginBottom: 40 }}>
          Effective {EFFECTIVE}
        </p>

        <Section n="1" title="Acceptance of Terms">
          By creating an account or using Outbindr ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
        </Section>

        <Section n="2" title="Description of Service">
          Outbindr is an AI-powered panel simulation tool. It allows users to configure virtual evaluation panels, submit ideas or projects, and receive AI-generated feedback and scoring. The Service is provided on a freemium basis — new accounts receive three (3) complimentary simulation sessions. Additional sessions require a paid subscription.
        </Section>

        <Section n="3" title="User Accounts">
          You must provide a valid email address and maintain the security of your account credentials. You are responsible for all activity that occurs under your account. You must be at least 13 years old to use the Service. If you are under 18, you represent that a parent or guardian has reviewed and agreed to these Terms.
        </Section>

        <Section n="4" title="Acceptable Use">
          You agree not to use the Service to generate or store content that is unlawful, abusive, harassing, defamatory, or that infringes third-party intellectual property rights. You may not attempt to reverse-engineer, scrape, or abuse the Service's API endpoints. You may not create multiple accounts to circumvent session limits.
        </Section>

        <Section n="5" title="AI-Generated Content">
          Responses generated by the Service are produced by large language models and are provided for informational and practice purposes only. Outbindr makes no warranty that AI-generated feedback is accurate, complete, or suitable for any particular purpose. AI output should not be treated as professional investment, legal, academic, or financial advice. You assume full responsibility for how you interpret and act on AI-generated content.
        </Section>

        <Section n="6" title="Intellectual Property">
          You retain ownership of any content you submit to the Service (pitch text, panel documents, etc.). By submitting content, you grant Outbindr a limited, non-exclusive licence to process that content solely to provide the Service. We do not claim ownership over your submissions and do not use them to train AI models.
        </Section>

        <Section n="7" title="Privacy">
          Your use of the Service is also governed by our{' '}
          <Link href="/privacy" style={{ color: '#000', textDecoration: 'underline' }}>Privacy Policy</Link>,
          which is incorporated into these Terms by reference.
        </Section>

        <Section n="8" title="Availability and Modifications">
          We may modify, suspend, or discontinue the Service at any time without notice. We may also update these Terms. Continued use of the Service after changes are posted constitutes acceptance of the revised Terms.
        </Section>

        <Section n="9" title="Disclaimer of Warranties">
          THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT ANY CONTENT IS ACCURATE.
        </Section>

        <Section n="10" title="Limitation of Liability">
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUTBINDR SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT PAID BY YOU TO OUTBINDR IN THE SIX MONTHS PRECEDING THE CLAIM.
        </Section>

        <Section n="11" title="Governing Law">
          These Terms are governed by the laws of the State of Delaware, United States, without regard to its conflict of law principles. Any disputes shall be resolved in the courts of Delaware.
        </Section>

        <Section n="12" title="Contact">
          For questions about these Terms, contact us at{' '}
          <a href="mailto:legal@outbindr.com" style={{ color: '#000' }}>legal@outbindr.com</a>.
        </Section>

        <div style={{ marginTop: 48, paddingTop: 24, borderTop: '1px solid #f0f0f0' }}>
          <Link href="/privacy" style={{ fontSize: 10, color: '#888', letterSpacing: '0.08em', marginRight: 24 }}>
            Privacy Policy →
          </Link>
          <Link href="/" style={{ fontSize: 10, color: '#888', letterSpacing: '0.08em' }}>
            ← Back to Outbindr
          </Link>
        </div>
      </div>
    </div>
  )
}

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 32 }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, marginBottom: 10 }}>
        <span style={{ fontSize: 9, color: '#ccc', letterSpacing: '0.12em', flexShrink: 0 }}>{n}.</span>
        <h2 style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.12em', color: '#000', margin: 0, textTransform: 'uppercase' }}>
          {title}
        </h2>
      </div>
      <p style={{ fontSize: 12, color: '#444', lineHeight: 1.8, margin: 0, paddingLeft: 22 }}>
        {children}
      </p>
    </div>
  )
}
